name: Knip

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  knip-backend:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Knip Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: backend/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --silent
      - name: Run knip (dead code / unused deps)
        run: yarn knip

  knip-frontend:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    name: Knip Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --silent
      - name: Generate middleware envs
        run: yarn generate:middleware-envs
      - name: Run knip (dead code / unused deps)
        run: yarn knip

  knip-admin:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin
    name: Knip Admin
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: admin/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --silent
      - name: Run knip (dead code / unused deps)
        run: yarn knip
