name: Lint

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  lint-backend:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Lint Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: backend/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts --silent
      - name: Run eslint (strict)
        run: yarn lint:strict
      - name: Check formatting
        run: yarn format:check

  lint-frontend:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    name: Lint Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts --silent
      - name: Generate middleware envs
        run: yarn generate:middleware-envs
      - name: Run eslint (strict)
        run: yarn lint:strict
      - name: Check formatting
        run: yarn format:check

  lint-admin:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin
    name: Lint Admin
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: admin/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts --silent
      - name: Run eslint (strict)
        run: yarn lint:strict
      - name: Check formatting
        run: yarn format:check
