name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  test-backend:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Unit Tests Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: backend/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --silent
      - name: Run unit tests
        run: yarn test

  test-frontend:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    name: Unit Tests Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --silent
      - name: Generate middleware envs
        run: yarn generate:middleware-envs
      - name: Run unit tests
        run: yarn test

  test-admin:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin
    name: Unit Tests Admin
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: admin/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile --silent
      - name: Run unit tests
        run: yarn test
